import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from './Home'
import Swiper from 'swiper'
import 'swiper/css'


const swiper = new Swiper()
function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}
const inter = Inter({ subsets: ['latin'] }) 

export default function Home() {
  return (
    <>
      <Head>
        <title>Maksymize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='css' href="/styles/custom.css"/>
        <link
      rel="stylesheet"
      type="text/css"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      
   />
      </Head>
    
    <HomePage />
    
    </>
  )
}
